name: run baseball power ratings

on:
  schedule:
    - cron: "0 11 * * *"   # Runs at 6:00 AM CDT (12:00 PM UTC)
    - cron: "0 15 * * *"   # Runs at 10:00 AM CDT (4:00 PM UTC)
    - cron: "0 19 * * *"   # Runs at 2:00 PM CDT (8:00 PM UTC)
    - cron: "0 23 * * *"    # Runs at 6:00 PM CDT (12:00 AM UTC next day)
    - cron: "0 3 * * *"    # Runs at 10:00 PM CDT (4:00 AM UTC next day)
  workflow_dispatch:  # Allows manual trigger if needed

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout only needed files
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/
            requirements.txt
            baseball_update.py
            PEAR/trebuc.ttf
            PEAR/Trebuchet MS Bold.ttf
            PEAR Baseball/
          sparse-checkout-cone-mode: true
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Fonts
        run: |
          mkdir -p ~/.fonts
          cp ./PEAR/trebuc.ttf ~/.fonts/
          cp ./PEAR/Trebuchet\ MS\ Bold.ttf ~/.fonts/
          fc-cache -f -v  # Rebuild font cache
          fc-list | grep "Trebuchet"  # Debug: Check if fonts are available

      - name: Run Python Script
        run: python baseball_update.py

      - name: Commit Changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "baseball update" --allow-empty)
      
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
